GET http://localhost:3000/api/v1/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ

###
GET http://localhost:3000/api/v1/profile/test

###

POST http://localhost:3000/api/v1/profile/language
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDk6MTY6NTcuMDg3WiIsIl9fdiI6MTN9LCJpYXQiOjE2MjYzNDA2Njl9.ka1dg0-JB2_ywPgA_PbcugfUUFVQT8ltWFWmcyJRf_8
Content-Type: application/json

{
    "name": "English",
    "efficiency":"Fluent"
}


###
GET http://localhost:3000/api/v1/profile/language
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ

###
GET http://localhost:3000/api/v1/profile/subject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ

###
GET http://localhost:3000/api/v1/profile/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ


###

POST http://localhost:3000/api/v1/profile/subject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ
Content-Type: application/json

{
    "name": "Guitar Guru",
    "rate":400,
    "description":"I'm a Software Developer with a years of experience as a Full Stack Web Developer. I'm mostly late to work with sometimes dissapering for hours in between work hours, but I can still teach you stuff."
}



###

POST http://localhost:3000/api/v1/profile/tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ
Content-Type: application/json

{
    "tags":["react","javascript","guitar"]
}



###
GET http://localhost:3000/api/v1/profile/education
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ


###

POST http://localhost:3000/api/v1/profile/education
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOnRydWUsIl9pZCI6IjYwZTE2YTE5NTU3ZDE0MDAxNTFjZGZlMSIsInVzZXJuYW1lIjoic2FtdWwtc2hyZXN0aGEiLCJlbWFpbCI6InNhbXVsc2hyZXN0aGExMDFAZ21haWwuY29tIiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMjEtMDctMDRUMDc6NTg6MTcuNzQyWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDctMTVUMDQ6MzI6MzQuNDk2WiIsIl9fdiI6MTB9LCJpYXQiOjE2MjYzMjcyNzB9.hGjOf51V_uHWsTruJ83CnOO69u9DpmCKGkkTyaB6TBQ
Content-Type: application/json

{
    "name": "Xavier Academy",
    "level":"Science",
    "years":"2013-2015"
}