POST http://localhost:3000/api/v1/user
Content-Type: application/json


{
    "firstname":"Samul",
    "lastname":"Shrestha",
    "password":"admin123",
    "email":"Samulshrestha101@gmail.com",
    "age":23,
    "userType":0,
    "username":"samul-shrestha",
    "gender":"Male"

}

###

GET http://localhost:3000/api/v1/user

###


POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email":"samulshrestha101@gmail.com",
    "password":"admin123"
}

###

POST http://localhost:3000/api/v1/user/logoutAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzVmVyaWZpZWQiOmZhbHNlLCJfaWQiOiI2MGRlZmExNTM5MTVhYjE2NzhiYzAxMmQiLCJ1c2VybmFtZSI6InNhbXVsLXNocmVzdGhhIiwiZW1haWwiOiJzYW11bHNocmVzdGhhMTAxQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoxLCJjcmVhdGVkQXQiOiIyMDIxLTA3LTAyVDExOjM1OjQ5LjIxN1oiLCJ1cGRhdGVkQXQiOiIyMDIxLTA3LTAyVDE1OjIyOjUwLjcwMVoiLCJfX3YiOjh9LCJpYXQiOjE2MjUyNTQ5Mzl9.Pl2Dhu6kQlXkyGzBv3K4bXA0CQKpRlagFkN68TsURWw

